# Generated by Django 4.2.6 on 2023-11-07 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youcanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
